FROM ghcr.io/nginx/nginx-unprivileged:1.31.3-alpine3.24-slim@sha256:22f839c5fb4007dc24d203a170a9e03fc185d660bfefc34ac6823a7aef085cbc

COPY web /usr/share/nginx/html/web
COPY src /usr/share/nginx/html/src
COPY e2e/nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY e2e/nginx/include-generated.conf /etc/nginx/conf.d/default.conf
