import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import test from 'node:test';
import {buildBoundedRealWorld,verifyBoundedRealWorld} from '../../tools/verification/bounded-real-world.mjs';
import {validateDeterministicProduct,validateProductIdentityMirror} from '../../tools/verification/run-protected-admission.mjs';
const sourceRoot=fileURLToPath(new URL('../../',import.meta.url));
test('bounded product repin requires independent deterministic bytes and an exact digest-only mirror',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-bounded-repin-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const first=await buildBoundedRealWorld(path.join(root,'first'),{sourceRoot});
 const second=await buildBoundedRealWorld(path.join(root,'second'),{sourceRoot});
 const verified=await verifyBoundedRealWorld(path.join(root,'second'));
 validateDeterministicProduct(first.productDigest,verified.productDigest);assert.equal(first.productDigest,second.productDigest);
 const old=`sha256:${'f'.repeat(64)}`,source=`assert.equal(productDigest, '${old}');`;
 assert.doesNotThrow(()=>validateProductIdentityMirror(source,source.replace(old,verified.productDigest),old,verified.productDigest));
 assert.throws(()=>validateProductIdentityMirror(source,'// removed proof',old,verified.productDigest),/mirror/);
 assert.throws(()=>validateDeterministicProduct(first.productDigest,old),/determinism/);
});
