import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import test from 'node:test';
import {buildQualificationWorld,qualificationTrustDescriptor} from '../../tools/verification/qualification-world.mjs';
const compose=fs.readFileSync(new URL('../../e2e/compose.github-hosted.yml',import.meta.url),'utf8');
const blocks=[...compose.matchAll(/node --input-type=module <<'NODE'\n([\s\S]*?)        NODE/g)];
assert.equal(blocks.length,2,'exact publication and web bootstrap scripts required');
test('actual Compose web bootstrap injects exact immutable trust before candidate modules',async t=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-compose-bootstrap-'));t.after(()=>fs.rmSync(temp,{recursive:true,force:true}));
 const source=path.join(temp,'source'),ready=path.join(temp,'ready');fs.mkdirSync(source);fs.mkdirSync(ready);
 const html='<!doctype html><head><script type="module" src="app.mjs"></script></head><body>Atlas</body>';
 fs.writeFileSync(path.join(source,'fullworld.html'),html);
 const descriptor=qualificationTrustDescriptor(await buildQualificationWorld(path.join(temp,'world')));
 const script=blocks[1][1].replace(/^        /gm,'').replaceAll("'/source-web'",JSON.stringify(source)).replaceAll("'/ready-web'",JSON.stringify(ready)).replaceAll("'/tmp/expected-web'",JSON.stringify(path.join(temp,'expected')));
 const run=value=>spawnSync(process.execPath,['--input-type=module'],{input:script,env:{...process.env,ATLAS_QUALIFICATION_TRUST_JSON:JSON.stringify(value??descriptor)},encoding:'utf8'});
 const first=run();assert.equal(first.status,0,first.stderr);
 const actual=fs.readFileSync(path.join(ready,'fullworld.html'),'utf8');
 assert.ok(actual.indexOf('atlas-protected-qualification-trust')<actual.indexOf('type="module"'));
 assert.match(actual,/writable: false, configurable: false/);
 assert.equal(fs.readFileSync(path.join(source,'fullworld.html'),'utf8'),html);
 assert.equal(run().status,0);
 assert.notEqual(run({...descriptor,fixtureId:'candidate'}).status,0);
 fs.appendFileSync(path.join(ready,'fullworld.html'),'drift');assert.notEqual(run().status,0);
 fs.writeFileSync(path.join(source,'fullworld.html'),'<script>candidate()</script>'+html);assert.notEqual(run().status,0);
});
