import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import test from 'node:test';
const root=fileURLToPath(new URL('../../',import.meta.url));
const compose=fs.readFileSync(path.join(root,'e2e/compose.github-hosted.yml'),'utf8');
const blocks=[...compose.matchAll(/node --input-type=module <<'NODE'\n([\s\S]*?)        NODE/g)];
assert.equal(blocks.length,2,'exact publication and web bootstrap scripts required');
test('actual Compose publication initializer binds environment identity and validates reentry',t=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-compose-ready-'));t.after(()=>fs.rmSync(temp,{recursive:true,force:true}));
 const source=path.join(temp,'source'),ready=path.join(temp,'ready');fs.mkdirSync(source);fs.mkdirSync(ready);fs.writeFileSync(path.join(source,'product.json'),'{"product":"exact"}');
 const script=blocks[0][1].replace(/^        /gm,'').replaceAll('/protected-control/',root).replaceAll("'/source'",JSON.stringify(source)).replaceAll("'/ready/fullworld'",JSON.stringify(path.join(ready,'fullworld')));
 const env={...process.env,GITHUB_REPOSITORY:'Oteryn/Oteryn-Atlas',GITHUB_RUN_ID:'42',ATLAS_E2E_SHARD:'1/1',ATLAS_CODE_REVISION:'a'.repeat(40),...Object.fromEntries(['ATLAS_PLAN_SEMANTIC_DIGEST','ATLAS_PLAN_INSTANCE_DIGEST','ATLAS_AUTHORITY_DIGEST','ATLAS_ENVIRONMENT_DIGEST'].map((key,i)=>[key,`sha256:${String(i).repeat(64)}`]))};
 const run=override=>spawnSync(process.execPath,['--input-type=module'],{input:script,env:{...env,...override},encoding:'utf8'});
 assert.equal(run().status,0);assert.equal(run().status,0);
 const manifest=JSON.parse(fs.readFileSync(path.join(ready,'fullworld/atlas-publication-readiness.json')));
 assert.equal(manifest.producerRunId,'42-1');assert.equal(manifest.candidateSha,env.ATLAS_CODE_REVISION);
 assert.notEqual(run({ATLAS_CODE_REVISION:'b'.repeat(40)}).status,0);
 assert.notEqual(run({ATLAS_E2E_SHARD:'0/1'}).status,0);
 fs.appendFileSync(path.join(ready,'fullworld/product.json'),'drift');assert.notEqual(run().status,0);
});
